### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
Fastlane "starter kit": you will need this for your [requested F-Droid listing](https://gitlab.com/fdroid/rfp/-/issues/1539). Please consider moving your screenshots into this structure as well. Be welcome to use my [Fastlane Cheat-Sheet](https://gitlab.com/snippets/1895688) as reference.

### CODE REVIEW

**Comment by ktprograms** [comment]
@IzzySoft Hello. Thank you for your help. This is my first time trying to get an app onto F-Droid.

Please confirm if I should move the screenshots into the fastlane folder first, or should I merge the pull request first?

**Comment by ktprograms** [comment]
Hi, @IzzySoft, should I remove the screenshots from the GitLab issue or not?

**Comment by IzzySoft** [comment]
@ktprograms short "instructions":

1. merge this MR (so the initial structure is there)
2. create the appropriate directory for the screenshots (`fastlane/metadata/en-US/images/phoneScreenshots`)
3. `git mv` the screenshots to the new location, adjust ReadMe (and where ever you have the screenshots linked from), commit
4. (optional) place your app's icon (ideally sized 512x512) as `fastlane/metadata/en-US/images/icon.png` and, if you wish and have, add `fastlane/metadata/en-US/images/featureGraphic.png` (size: 1024x500 or 512x250)
5. (again optional) build upon the structure by adding e.g. `title.txt`, `video.txt`, per-release changelogs
6. when done (for now; steps 3-5 can also be postponed for a later release) let me know so I cross-check (to give you some backing/confidence)
7. when all is fine, `git tag` it – as F-Droid picks Fastlane from the same tag it builds the APK from.

Whenever there are questions, don't hesitate asking them. We gladly assist (disclosure: I'm one of the F-Droid maintainers).

**Comment by IzzySoft** [comment]
Thanks, good job building on this – looks perfect! :tada:

**Comment by ktprograms** [comment]
Thanks!

**Comment by IzzySoft** [comment]
Gladly! To confirm it works, I just triggered the update manually (without sync, so it's not yet live):

```
com.ktprograms.watertracker: 0.1.0-beta/0.1.1, GH https://github.com/ktprograms/WaterTracker/releases: https://github.com/ktprograms/WaterTracker/releases/download/v0.1.1-beta/WaterTracker0.1.1beta.apk
- Grabbing update for com.ktprograms.watertracker: OK
- Checking '/web/ftp/repo/fdroid/repo/com.ktprograms.watertracker_2.apk' for libraries and malware …
com.ktprograms.watertracker: calling 'getFastlaneMeta(github,[host:github.com,owner:ktprograms,repo:WaterTracker,path:/fastlane/metadata/android])'
com.ktprograms.watertracker: FastlaneFeatures title,shortdesc,fulldescMD,icon
com.ktprograms.watertracker: looking for 'https://api.github.com/repos/ktprograms/WaterTracker/contents/fastlane%2Fmetadata%2Fandroid'
com.ktprograms.watertracker: looking for 'https://api.github.com/repos/ktprograms/WaterTracker/contents/fastlane%2Fmetadata%2Fandroid%2Fde'
com.ktprograms.watertracker: looking for 'https://api.github.com/repos/ktprograms/WaterTracker/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US'
com.ktprograms.watertracker: looking for 'https://api.github.com/repos/ktprograms/WaterTracker/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages'
com.ktprograms.watertracker: looking for 'https://api.github.com/repos/ktprograms/WaterTracker/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages%2FphoneScreenshots'
com.ktprograms.watertracker: checking locale 'de'
com.ktprograms.watertracker: updating '/web/ftp/repo/fdroid/metadata/com.ktprograms.watertracker/de/short_description.txt'
com.ktprograms.watertracker: checking locale 'en-US'
com.ktprograms.watertracker: updating '/web/ftp/repo/fdroid/metadata/com.ktprograms.watertracker/en-US/short_description.txt'
com.ktprograms.watertracker: updating '/web/ftp/repo/fdroid/metadata/com.ktprograms.watertracker/en-US/title.txt'
com.ktprograms.watertracker: updating '/web/ftp/repo/fdroid/repo/com.ktprograms.watertracker/en-US/icon.png'
```

So it works fine! It also pulled the changelog (I just notice the logging is missing for that – fixed now "for next time").

**Comment by ktprograms** [comment]
Yay!

**Pull request merged**
